
package com.example.ceshisuan.Download;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UploadFileServiceImplService", targetNamespace = "http://impl.ws_demo/", wsdlLocation = "http://localhost:8081/wsServeice2?wsdl")
public class UploadFileServiceImplService
    extends Service
{

    private final static URL UPLOADFILESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPLOADFILESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName UPLOADFILESERVICEIMPLSERVICE_QNAME = new QName("http://impl.ws_demo/", "UploadFileServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/wsServeice2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPLOADFILESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        UPLOADFILESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public UploadFileServiceImplService() {
        super(__getWsdlLocation(), UPLOADFILESERVICEIMPLSERVICE_QNAME);
    }

    public UploadFileServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPLOADFILESERVICEIMPLSERVICE_QNAME, features);
    }

    public UploadFileServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, UPLOADFILESERVICEIMPLSERVICE_QNAME);
    }

    public UploadFileServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPLOADFILESERVICEIMPLSERVICE_QNAME, features);
    }

    public UploadFileServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadFileServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UploadFileServiceImpl
     */
    @WebEndpoint(name = "UploadFileServiceImplPort")
    public UploadFileServiceImpl getUploadFileServiceImplPort() {
        return super.getPort(new QName("http://impl.ws_demo/", "UploadFileServiceImplPort"), UploadFileServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UploadFileServiceImpl
     */
    @WebEndpoint(name = "UploadFileServiceImplPort")
    public UploadFileServiceImpl getUploadFileServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws_demo/", "UploadFileServiceImplPort"), UploadFileServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPLOADFILESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw UPLOADFILESERVICEIMPLSERVICE_EXCEPTION;
        }
        return UPLOADFILESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
