
package com.example.ceshisuan.Download;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UploadFileServiceImpl", targetNamespace = "http://impl.ws_demo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UploadFileServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "getValue", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.Download.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.Download.GetValueResponse")
    @Action(input = "http://impl.ws_demo/UploadFileServiceImpl/getValueRequest", output = "http://impl.ws_demo/UploadFileServiceImpl/getValueResponse")
    public void getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "writeFile", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.Download.WriteFile")
    @ResponseWrapper(localName = "writeFileResponse", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.Download.WriteFileResponse")
    @Action(input = "http://impl.ws_demo/UploadFileServiceImpl/writeFileRequest", output = "http://impl.ws_demo/UploadFileServiceImpl/writeFileResponse")
    public int writeFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1);

}
