
package com.example.ceshisuan.test3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AttachmentEngineImplService", targetNamespace = "http://impl.ws_demo/", wsdlLocation = "http://localhost:8081/wsServeice3?wsdl")
public class AttachmentEngineImplService
    extends Service
{

    private final static URL ATTACHMENTENGINEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ATTACHMENTENGINEIMPLSERVICE_EXCEPTION;
    private final static QName ATTACHMENTENGINEIMPLSERVICE_QNAME = new QName("http://impl.ws_demo/", "AttachmentEngineImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/wsServeice3?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATTACHMENTENGINEIMPLSERVICE_WSDL_LOCATION = url;
        ATTACHMENTENGINEIMPLSERVICE_EXCEPTION = e;
    }

    public AttachmentEngineImplService() {
        super(__getWsdlLocation(), ATTACHMENTENGINEIMPLSERVICE_QNAME);
    }

    public AttachmentEngineImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATTACHMENTENGINEIMPLSERVICE_QNAME, features);
    }

    public AttachmentEngineImplService(URL wsdlLocation) {
        super(wsdlLocation, ATTACHMENTENGINEIMPLSERVICE_QNAME);
    }

    public AttachmentEngineImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATTACHMENTENGINEIMPLSERVICE_QNAME, features);
    }

    public AttachmentEngineImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AttachmentEngineImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AttachmentEngine
     */
    @WebEndpoint(name = "AttachmentEngineImplPort")
    public AttachmentEngine getAttachmentEngineImplPort() {
        return super.getPort(new QName("http://impl.ws_demo/", "AttachmentEngineImplPort"), AttachmentEngine.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AttachmentEngine
     */
    @WebEndpoint(name = "AttachmentEngineImplPort")
    public AttachmentEngine getAttachmentEngineImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws_demo/", "AttachmentEngineImplPort"), AttachmentEngine.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATTACHMENTENGINEIMPLSERVICE_EXCEPTION!= null) {
            throw ATTACHMENTENGINEIMPLSERVICE_EXCEPTION;
        }
        return ATTACHMENTENGINEIMPLSERVICE_WSDL_LOCATION;
    }

}
