
package com.example.ceshisuan.util;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImpl", targetNamespace = "http://impl.ws_demo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.example.ceshisuan.util.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHelloResponse")
    @Action(input = "http://impl.ws_demo/WebServiceImpl/sayHelloRequest", output = "http://impl.ws_demo/WebServiceImpl/sayHelloResponse")
    public User sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello1", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHello1")
    @ResponseWrapper(localName = "sayHello1Response", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHello1Response")
    @Action(input = "http://impl.ws_demo/WebServiceImpl/sayHello1Request", output = "http://impl.ws_demo/WebServiceImpl/sayHello1Response")
    public String sayHello1(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello2", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHello2")
    @ResponseWrapper(localName = "sayHello2Response", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHello2Response")
    @Action(input = "http://impl.ws_demo/WebServiceImpl/sayHello2Request", output = "http://impl.ws_demo/WebServiceImpl/sayHello2Response")
    public String sayHello2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello3", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHello3")
    @ResponseWrapper(localName = "sayHello3Response", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHello3Response")
    @Action(input = "http://impl.ws_demo/WebServiceImpl/sayHello3Request", output = "http://impl.ws_demo/WebServiceImpl/sayHello3Response")
    public String sayHello3(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello4", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHello4")
    @ResponseWrapper(localName = "sayHello4Response", targetNamespace = "http://impl.ws_demo/", className = "com.example.ceshisuan.util.SayHello4Response")
    @Action(input = "http://impl.ws_demo/WebServiceImpl/sayHello4Request", output = "http://impl.ws_demo/WebServiceImpl/sayHello4Response")
    public String sayHello4(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
