package com.example.ceshisuan.ws_02;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2019-03-08T19:30:55.832+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", name = "ListsSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ListsSoap {

    @WebMethod(operationName = "DeleteContentTypeXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteContentTypeXmlDocument")
    @RequestWrapper(localName = "DeleteContentTypeXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "DeleteContentTypeXmlDocument")
    @ResponseWrapper(localName = "DeleteContentTypeXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "DeleteContentTypeXmlDocumentResponse")
    @WebResult(name = "DeleteContentTypeXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public DeleteContentTypeXmlDocumentResponse.DeleteContentTypeXmlDocumentResult deleteContentTypeXmlDocument(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String contentTypeId,
            @WebParam(name = "documentUri", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String documentUri
    );

    @WebMethod(operationName = "GetListItemChangesSinceToken", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChangesSinceToken")
    @RequestWrapper(localName = "GetListItemChangesSinceToken", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListItemChangesSinceToken")
    @ResponseWrapper(localName = "GetListItemChangesSinceTokenResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListItemChangesSinceTokenResponse")
    @WebResult(name = "GetListItemChangesSinceTokenResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListItemChangesSinceTokenResponse.GetListItemChangesSinceTokenResult getListItemChangesSinceToken(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String viewName,
            @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChangesSinceToken.Query query,
            @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChangesSinceToken.ViewFields viewFields,
            @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String rowLimit,
            @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChangesSinceToken.QueryOptions queryOptions,
            @WebParam(name = "changeToken", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String changeToken,
            @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChangesSinceToken.Contains contains
    );

    @WebMethod(operationName = "AddList", action = "http://schemas.microsoft.com/sharepoint/soap/AddList")
    @RequestWrapper(localName = "AddList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddList")
    @ResponseWrapper(localName = "AddListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddListResponse")
    @WebResult(name = "AddListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public AddListResponse.AddListResult addList(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String description,
            @WebParam(name = "templateID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    int templateID
    );

    @WebMethod(operationName = "AddAttachment", action = "http://schemas.microsoft.com/sharepoint/soap/AddAttachment")
    @RequestWrapper(localName = "AddAttachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddAttachment")
    @ResponseWrapper(localName = "AddAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddAttachmentResponse")
    @WebResult(name = "AddAttachmentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public String addAttachment(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listItemID,
            @WebParam(name = "fileName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String fileName,
            @WebParam(name = "attachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    byte[] attachment
    );

    @WebMethod(operationName = "UpdateList", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateList")
    @RequestWrapper(localName = "UpdateList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateList")
    @ResponseWrapper(localName = "UpdateListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateListResponse")
    @WebResult(name = "UpdateListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public UpdateListResponse.UpdateListResult updateList(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "listProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateList.ListProperties listProperties,
            @WebParam(name = "newFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateList.NewFields newFields,
            @WebParam(name = "updateFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateList.UpdateFields updateFields,
            @WebParam(name = "deleteFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateList.DeleteFields deleteFields,
            @WebParam(name = "listVersion", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listVersion
    );

    @WebMethod(operationName = "GetList", action = "http://schemas.microsoft.com/sharepoint/soap/GetList")
    @RequestWrapper(localName = "GetList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetList")
    @ResponseWrapper(localName = "GetListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListResponse")
    @WebResult(name = "GetListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListResponse.GetListResult getList(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName
    );

    @WebMethod(operationName = "CheckOutFile", action = "http://schemas.microsoft.com/sharepoint/soap/CheckOutFile")
    @RequestWrapper(localName = "CheckOutFile", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CheckOutFile")
    @ResponseWrapper(localName = "CheckOutFileResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CheckOutFileResponse")
    @WebResult(name = "CheckOutFileResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public boolean checkOutFile(
            @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String pageUrl,
            @WebParam(name = "checkoutToLocal", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String checkoutToLocal,
            @WebParam(name = "lastmodified", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String lastmodified
    );

    @WebMethod(operationName = "GetListContentTypes", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentTypes")
    @RequestWrapper(localName = "GetListContentTypes", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListContentTypes")
    @ResponseWrapper(localName = "GetListContentTypesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListContentTypesResponse")
    @WebResult(name = "GetListContentTypesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListContentTypesResponse.GetListContentTypesResult getListContentTypes(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String contentTypeId
    );

    @WebMethod(operationName = "UpdateContentTypeXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypeXmlDocument")
    @RequestWrapper(localName = "UpdateContentTypeXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateContentTypeXmlDocument")
    @ResponseWrapper(localName = "UpdateContentTypeXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateContentTypeXmlDocumentResponse")
    @WebResult(name = "UpdateContentTypeXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public UpdateContentTypeXmlDocumentResponse.UpdateContentTypeXmlDocumentResult updateContentTypeXmlDocument(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String contentTypeId,
            @WebParam(name = "newDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateContentTypeXmlDocument.NewDocument newDocument
    );

    @WebMethod(operationName = "CheckInFile", action = "http://schemas.microsoft.com/sharepoint/soap/CheckInFile")
    @RequestWrapper(localName = "CheckInFile", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CheckInFile")
    @ResponseWrapper(localName = "CheckInFileResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CheckInFileResponse")
    @WebResult(name = "CheckInFileResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public boolean checkInFile(
            @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String pageUrl,
            @WebParam(name = "comment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String comment,
            @WebParam(name = "CheckinType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String checkinType
    );

    @WebMethod(operationName = "UpdateContentType", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentType")
    @RequestWrapper(localName = "UpdateContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateContentType")
    @ResponseWrapper(localName = "UpdateContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateContentTypeResponse")
    @WebResult(name = "UpdateContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public UpdateContentTypeResponse.UpdateContentTypeResult updateContentType(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String contentTypeId,
            @WebParam(name = "contentTypeProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateContentType.ContentTypeProperties contentTypeProperties,
            @WebParam(name = "newFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateContentType.NewFields newFields,
            @WebParam(name = "updateFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateContentType.UpdateFields updateFields,
            @WebParam(name = "deleteFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateContentType.DeleteFields deleteFields,
            @WebParam(name = "addToView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String addToView
    );

    @WebMethod(operationName = "AddDiscussionBoardItem", action = "http://schemas.microsoft.com/sharepoint/soap/AddDiscussionBoardItem")
    @RequestWrapper(localName = "AddDiscussionBoardItem", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddDiscussionBoardItem")
    @ResponseWrapper(localName = "AddDiscussionBoardItemResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddDiscussionBoardItemResponse")
    @WebResult(name = "AddDiscussionBoardItemResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public AddDiscussionBoardItemResponse.AddDiscussionBoardItemResult addDiscussionBoardItem(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "message", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    byte[] message
    );

    @WebMethod(operationName = "AddListFromFeature", action = "http://schemas.microsoft.com/sharepoint/soap/AddListFromFeature")
    @RequestWrapper(localName = "AddListFromFeature", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddListFromFeature")
    @ResponseWrapper(localName = "AddListFromFeatureResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddListFromFeatureResponse")
    @WebResult(name = "AddListFromFeatureResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public AddListFromFeatureResponse.AddListFromFeatureResult addListFromFeature(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "description", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String description,
            @WebParam(name = "featureID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String featureID,
            @WebParam(name = "templateID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    int templateID
    );

    @WebMethod(operationName = "GetListCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetListCollection")
    @RequestWrapper(localName = "GetListCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListCollection")
    @ResponseWrapper(localName = "GetListCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListCollectionResponse")
    @WebResult(name = "GetListCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListCollectionResponse.GetListCollectionResult getListCollection();

    @WebMethod(operationName = "UpdateListItems", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateListItems")
    @RequestWrapper(localName = "UpdateListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateListItems")
    @ResponseWrapper(localName = "UpdateListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateListItemsResponse")
    @WebResult(name = "UpdateListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public UpdateListItemsResponse.UpdateListItemsResult updateListItems(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "updates", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateListItems.Updates updates
    );

    @WebMethod(operationName = "UndoCheckOut", action = "http://schemas.microsoft.com/sharepoint/soap/UndoCheckOut")
    @RequestWrapper(localName = "UndoCheckOut", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UndoCheckOut")
    @ResponseWrapper(localName = "UndoCheckOutResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UndoCheckOutResponse")
    @WebResult(name = "UndoCheckOutResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public boolean undoCheckOut(
            @WebParam(name = "pageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String pageUrl
    );

    @WebMethod(operationName = "GetListAndView", action = "http://schemas.microsoft.com/sharepoint/soap/GetListAndView")
    @RequestWrapper(localName = "GetListAndView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListAndView")
    @ResponseWrapper(localName = "GetListAndViewResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListAndViewResponse")
    @WebResult(name = "GetListAndViewResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListAndViewResponse.GetListAndViewResult getListAndView(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String viewName
    );

    @WebMethod(operationName = "DeleteAttachment", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteAttachment")
    @RequestWrapper(localName = "DeleteAttachment", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "DeleteAttachment")
    @ResponseWrapper(localName = "DeleteAttachmentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "DeleteAttachmentResponse")
    public void deleteAttachment(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listItemID,
            @WebParam(name = "url", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String url
    );

    @WebMethod(operationName = "CreateContentType", action = "http://schemas.microsoft.com/sharepoint/soap/CreateContentType")
    @RequestWrapper(localName = "CreateContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CreateContentType")
    @ResponseWrapper(localName = "CreateContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CreateContentTypeResponse")
    @WebResult(name = "CreateContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public String createContentType(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "displayName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String displayName,
            @WebParam(name = "parentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String parentType,
            @WebParam(name = "fields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    CreateContentType.Fields fields,
            @WebParam(name = "contentTypeProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    CreateContentType.ContentTypeProperties contentTypeProperties,
            @WebParam(name = "addToView", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String addToView
    );

    @WebMethod(operationName = "GetListItems", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItems")
    @RequestWrapper(localName = "GetListItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListItems")
    @ResponseWrapper(localName = "GetListItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListItemsResponse")
    @WebResult(name = "GetListItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListItemsResponse.GetListItemsResult getListItems(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String viewName,
            @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItems.Query query,
            @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItems.ViewFields viewFields,
            @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String rowLimit,
            @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItems.QueryOptions queryOptions,
            @WebParam(name = "webID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String webID
    );

    @WebMethod(operationName = "DeleteContentType", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteContentType")
    @RequestWrapper(localName = "DeleteContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "DeleteContentType")
    @ResponseWrapper(localName = "DeleteContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "DeleteContentTypeResponse")
    @WebResult(name = "DeleteContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public DeleteContentTypeResponse.DeleteContentTypeResult deleteContentType(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String contentTypeId
    );

    @WebMethod(operationName = "GetListContentTypesAndProperties", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentTypesAndProperties")
    @RequestWrapper(localName = "GetListContentTypesAndProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListContentTypesAndProperties")
    @ResponseWrapper(localName = "GetListContentTypesAndPropertiesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListContentTypesAndPropertiesResponse")
    @WebResult(name = "GetListContentTypesAndPropertiesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListContentTypesAndPropertiesResponse.GetListContentTypesAndPropertiesResult getListContentTypesAndProperties(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String contentTypeId,
            @WebParam(name = "propertyPrefix", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String propertyPrefix,
            @WebParam(name = "includeWebProperties", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    Boolean includeWebProperties
    );

    @WebMethod(operationName = "AddWikiPage", action = "http://schemas.microsoft.com/sharepoint/soap/AddWikiPage")
    @RequestWrapper(localName = "AddWikiPage", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddWikiPage")
    @ResponseWrapper(localName = "AddWikiPageResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "AddWikiPageResponse")
    @WebResult(name = "AddWikiPageResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public AddWikiPageResponse.AddWikiPageResult addWikiPage(
            @WebParam(name = "strListName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String strListName,
            @WebParam(name = "listRelPageUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listRelPageUrl,
            @WebParam(name = "wikiContent", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String wikiContent
    );

    @WebMethod(operationName = "GetListItemChangesWithKnowledge", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChangesWithKnowledge")
    @RequestWrapper(localName = "GetListItemChangesWithKnowledge", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListItemChangesWithKnowledge")
    @ResponseWrapper(localName = "GetListItemChangesWithKnowledgeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListItemChangesWithKnowledgeResponse")
    @WebResult(name = "GetListItemChangesWithKnowledgeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListItemChangesWithKnowledgeResponse.GetListItemChangesWithKnowledgeResult getListItemChangesWithKnowledge(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "viewName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String viewName,
            @WebParam(name = "query", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChangesWithKnowledge.Query query,
            @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChangesWithKnowledge.ViewFields viewFields,
            @WebParam(name = "rowLimit", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String rowLimit,
            @WebParam(name = "queryOptions", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChangesWithKnowledge.QueryOptions queryOptions,
            @WebParam(name = "syncScope", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String syncScope,
            @WebParam(name = "knowledge", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChangesWithKnowledge.Knowledge knowledge,
            @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChangesWithKnowledge.Contains contains
    );

    @WebMethod(operationName = "UpdateListItemsWithKnowledge", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateListItemsWithKnowledge")
    @RequestWrapper(localName = "UpdateListItemsWithKnowledge", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateListItemsWithKnowledge")
    @ResponseWrapper(localName = "UpdateListItemsWithKnowledgeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateListItemsWithKnowledgeResponse")
    @WebResult(name = "UpdateListItemsWithKnowledgeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public UpdateListItemsWithKnowledgeResponse.UpdateListItemsWithKnowledgeResult updateListItemsWithKnowledge(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "updates", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateListItemsWithKnowledge.Updates updates,
            @WebParam(name = "syncScope", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String syncScope,
            @WebParam(name = "knowledge", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateListItemsWithKnowledge.Knowledge knowledge
    );

    @WebMethod(operationName = "GetListItemChanges", action = "http://schemas.microsoft.com/sharepoint/soap/GetListItemChanges")
    @RequestWrapper(localName = "GetListItemChanges", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListItemChanges")
    @ResponseWrapper(localName = "GetListItemChangesResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListItemChangesResponse")
    @WebResult(name = "GetListItemChangesResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListItemChangesResponse.GetListItemChangesResult getListItemChanges(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "viewFields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChanges.ViewFields viewFields,
            @WebParam(name = "since", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String since,
            @WebParam(name = "contains", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    GetListItemChanges.Contains contains
    );

    @WebMethod(operationName = "GetAttachmentCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetAttachmentCollection")
    @RequestWrapper(localName = "GetAttachmentCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetAttachmentCollection")
    @ResponseWrapper(localName = "GetAttachmentCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetAttachmentCollectionResponse")
    @WebResult(name = "GetAttachmentCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetAttachmentCollectionResponse.GetAttachmentCollectionResult getAttachmentCollection(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "listItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listItemID
    );

    @WebMethod(operationName = "DeleteList", action = "http://schemas.microsoft.com/sharepoint/soap/DeleteList")
    @RequestWrapper(localName = "DeleteList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "DeleteList")
    @ResponseWrapper(localName = "DeleteListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "DeleteListResponse")
    public void deleteList(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName
    );

    @WebMethod(operationName = "UpdateContentTypesXmlDocument", action = "http://schemas.microsoft.com/sharepoint/soap/UpdateContentTypesXmlDocument")
    @RequestWrapper(localName = "UpdateContentTypesXmlDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateContentTypesXmlDocument")
    @ResponseWrapper(localName = "UpdateContentTypesXmlDocumentResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "UpdateContentTypesXmlDocumentResponse")
    @WebResult(name = "UpdateContentTypesXmlDocumentResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public UpdateContentTypesXmlDocumentResponse.UpdateContentTypesXmlDocumentResult updateContentTypesXmlDocument(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "newDocument", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    UpdateContentTypesXmlDocument.NewDocument newDocument
    );

    @WebMethod(operationName = "GetListContentType", action = "http://schemas.microsoft.com/sharepoint/soap/GetListContentType")
    @RequestWrapper(localName = "GetListContentType", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListContentType")
    @ResponseWrapper(localName = "GetListContentTypeResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetListContentTypeResponse")
    @WebResult(name = "GetListContentTypeResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetListContentTypeResponse.GetListContentTypeResult getListContentType(
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName,
            @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String contentTypeId
    );

    @WebMethod(operationName = "ApplyContentTypeToList", action = "http://schemas.microsoft.com/sharepoint/soap/ApplyContentTypeToList")
    @RequestWrapper(localName = "ApplyContentTypeToList", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "ApplyContentTypeToList")
    @ResponseWrapper(localName = "ApplyContentTypeToListResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "ApplyContentTypeToListResponse")
    @WebResult(name = "ApplyContentTypeToListResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public ApplyContentTypeToListResponse.ApplyContentTypeToListResult applyContentTypeToList(
            @WebParam(name = "webUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String webUrl,
            @WebParam(name = "contentTypeId", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String contentTypeId,
            @WebParam(name = "listName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String listName
    );

    @WebMethod(operationName = "GetVersionCollection", action = "http://schemas.microsoft.com/sharepoint/soap/GetVersionCollection")
    @RequestWrapper(localName = "GetVersionCollection", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetVersionCollection")
    @ResponseWrapper(localName = "GetVersionCollectionResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetVersionCollectionResponse")
    @WebResult(name = "GetVersionCollectionResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
    public GetVersionCollectionResponse.GetVersionCollectionResult getVersionCollection(
            @WebParam(name = "strlistID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String strlistID,
            @WebParam(name = "strlistItemID", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String strlistItemID,
            @WebParam(name = "strFieldName", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String strFieldName
    );
}
