package com.example.ceshisuan.ws_demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2019-03-08T18:35:24.983+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", name = "CopySoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CopySoap {

    @WebMethod(operationName = "GetItem", action = "http://schemas.microsoft.com/sharepoint/soap/GetItem")
    @RequestWrapper(localName = "GetItem", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetItem")
    @ResponseWrapper(localName = "GetItemResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "GetItemResponse")
    public void getItem(
            @WebParam(name = "Url", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String url,
            @WebParam(mode = WebParam.Mode.OUT, name = "GetItemResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    javax.xml.ws.Holder<Long> getItemResult,
            @WebParam(mode = WebParam.Mode.OUT, name = "Fields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    javax.xml.ws.Holder<FieldInformationCollection> fields,
            @WebParam(mode = WebParam.Mode.OUT, name = "Stream", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    javax.xml.ws.Holder<byte[]> stream
    );

    @WebMethod(operationName = "CopyIntoItemsLocal", action = "http://schemas.microsoft.com/sharepoint/soap/CopyIntoItemsLocal")
    @RequestWrapper(localName = "CopyIntoItemsLocal", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CopyIntoItemsLocal")
    @ResponseWrapper(localName = "CopyIntoItemsLocalResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CopyIntoItemsLocalResponse")
    public void copyIntoItemsLocal(
            @WebParam(name = "SourceUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String sourceUrl,
            @WebParam(name = "DestinationUrls", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    DestinationUrlCollection destinationUrls,
            @WebParam(mode = WebParam.Mode.OUT, name = "CopyIntoItemsLocalResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    javax.xml.ws.Holder<Long> copyIntoItemsLocalResult,
            @WebParam(mode = WebParam.Mode.OUT, name = "Results", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    javax.xml.ws.Holder<CopyResultCollection> results
    );

    @WebMethod(operationName = "CopyIntoItems", action = "http://schemas.microsoft.com/sharepoint/soap/CopyIntoItems")
    @RequestWrapper(localName = "CopyIntoItems", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CopyIntoItems")
    @ResponseWrapper(localName = "CopyIntoItemsResponse", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/", className = "CopyIntoItemsResponse")
    public void copyIntoItems(
            @WebParam(name = "SourceUrl", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    String sourceUrl,
            @WebParam(name = "DestinationUrls", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    DestinationUrlCollection destinationUrls,
            @WebParam(name = "Fields", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    FieldInformationCollection fields,
            @WebParam(name = "Stream", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    byte[] stream,
            @WebParam(mode = WebParam.Mode.OUT, name = "CopyIntoItemsResult", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    javax.xml.ws.Holder<Long> copyIntoItemsResult,
            @WebParam(mode = WebParam.Mode.OUT, name = "Results", targetNamespace = "http://schemas.microsoft.com/sharepoint/soap/")
                    javax.xml.ws.Holder<CopyResultCollection> results
    );
}
